name: Report und Artefakt

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository herunterladen
        uses: actions/checkout@v4

      - name: Skript ausführbar machen
        run: chmod +x scripts/*.sh

      - name: Skript ausführen
        run: bash scripts/04_create_report.sh

  
      - name: Report Hochladen
        uses: actions/upload-artifact@v4
        with:
          name: namen-report
          path: output/report.txt